version: '3.8'

#
# To use: make sure the following environment variables are set:
# Required:
# REPLICAS
# CPUS
# MEMORY
# TAG
# PROJECT_NAME
# DTR
# TRAEFIK_HOST
# TRAEFIK_WHITELIST (required)
# LOGS_ENABLED (switch log collection for the container on or off, TRUE or FALSE)
# LOGS_RECEIVER_URLS=<URL, URL, URL> - set multiple log destinations. The URL should include the token or index of an Elasticsearch API endpoint. E.g. https://logsene-receiver.sematext.com/<YOUR_LOGS_TOKEN>. Does NOT require setting the LOGS_TOKEN env var separately.


# If stateful volume is needed for your project uncomment this section:
#volumes:
#  (the next line is the internal name for the volume, used in the service specification
#  data:
#      name: ${PROJECT_NAME}-data
#      (the next line is no longer indented above the volume name)
#      external: true

#If you are using the shared IP blacklist for Tomcat uncomment this section:, here the internal name matches the external name
#volumes:
#  ops-shared-data:
#      name: ops-shared-data
#      external: true 

services:
  service:
    image: ${DTR}${PROJECT_NAME}:${TAG}
    environment:
      - BASE_URL=${BASE_URL}
      - CAS_BASE=${CAS_BASE}
      - IS_AUTH_URL=${IS_AUTH_URL}
      - EBIRD_PREFS_URL=${EBIRD_PREFS_URL}
      - EBIRD_API_BASE=${EBIRD_API_BASE}
      - EBIRD_API_KEY=${EBIRD_API_KEY}
      - ML_DOWNLOAD_BASE=${ML_DOWNLOAD_BASE}
      - EBIRD_WEB_BASE=${EBIRD_WEB_BASE}
    #optional, you may not need any secrets, eg. db password
    #secrets:
    #  - $(PROJECT_NAME).foo
    networks:
      - is-1
    #healthcheck:
    #  test: wget --quiet --spider http://localhost:8080 || exit 1
    #  start_period: 15s
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    #Uncomment this section if using a volume - note there are two volumes, one for your
    #app and one for the shared tomcat IP blacklist, uncomment one or both as required
    #volumes:
    #  - type: volume
    #    source: data
    #    target: #directory within your container that contains stateful data
    #    volume:
    #      # don't copy contents of container over the mount location, you might remove this line
    #      nocopy: true
    #  - type: volume
    #    source: ops-shared-data
    #    target: /mnt/ops-shared-data
    #    volume:
    #      nocopy: true
    deploy:
      placement:
        constraints:
          - node.labels.workloads != false
      replicas: ${REPLICAS}
        # rolling updates 1 container at a time, wait 5m, rollback if fail (not pause)
      update_config: 
        parallelism: 1
        delay: 5m
        failure_action: rollback
        order: start-first
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
      labels:
          # whitelist: only CLO and clo.isvpn addresses
          # CLO:       128.84.6.0/23
          # clo.vpn:   10.17.59.0/24
          # clo.isvpn: 10.17.44.0/24
          # PRTG:      132.236.118.183
          # All AWS private subnets, test and production accounts:     10.92.220.0/22
          # WHITELIST is NOT optional
          #     test - consider commenting out the value in test.env so that you get the default whitelist from this file
          #     production - use 0.0.0.0/0 in prod.env if the app is public, always use a whitelist in test because test is exposed to the world!
          # see .env files in ops-ddc-deploy for suggested networks
        - "traefik.frontend.whiteList.sourceRange=${TRAEFIK_WHITELIST:-128.253.169.76,128.253.169.77,128.84.6.0/23,128.84.106.0/24,10.17.44.0/24,10.17.121.0/24,10.17.175.0/24,132.236.118.0/24,10.92.220.0/22,10.17.59.0/24}"
        - "com.docker.ucp.access.label=/ml"
        - "traefik.docker.network=is-1"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:${TRAEFIK_HOST}"
        - "traefik.frontend.passHostHeader=true"
        #- "traefik.backend.loadbalancer.stickiness=true"
          #- "traefik.frontend.headers.SSLRedirect=true"
          #  above label has a bug with pathprefixstrip option.  use below instead to redirect http to https
        - "traefik.frontend.redirect.entryPoint=https"
          

#as with above secret this is optional, it is called out here because it is created external to project
#secrets:
#  ${PROJECT_NAME}.properties:
#    external: true
    
networks:
  #same network as above, ie ask devops
  is-1:
    external: true