export interface PrefsModel {
	PROFILE_VISITS_OPT_IN: string,
	PRIVACY_POLICY_ACCEPTED: string,
	USE_24H: string,
	PROFILE_OPT_IN: string,
	SHOW_SUBSPECIES: string,
	SMART_CHECKLIST: string,
	DISPLAY_NAME_PREF: string,
	VISITS_OPT_OUT: string,
	DISPLAY_COMMON_NAME: string,
	DISPLAY_SCIENTIFIC_NAME: string,
	PROFILE_REGION: string,
	SHOW_COMMENTS: string,
	COMMON_NAME_LOCALE: string,
	GMAP_TYPE: string,
	ALERTS_OPT_OUT: string,
	EMAIL_CS: string,
	TOP100_OPT_OUT: string,
	DIST_UNIT: string
};
